# Server
server:
  compression:
    enabled: true
  http2:
    enabled: true
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /arduino-websocket/api/

spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  security-util:
    jwtExpirationTime: ${ENV_SP_JWT_EXPIRATION_TIME:7776000000}
    securitySecret: ${ENV_SP_SECURITY_SECRET:arduino-api}
    allowedOrigins:
      - "http://172.17.0.1"
      - "http://arduino.dev.local.net"
      - "http://localhost:3150"
      - "https://arduino.app-workspace.com"
    openUrl:
      - "/swagger-resources/**"
      - "/swagger-ui.html/**"
      - "/swagger-config/**"
      - "/source-handler/**"
      - "/authorization"
      - "/swagger-ui/**"
      - "/favicon.ico/**"
      - "/v3/api-docs/**"
      - "/v3/api-docs"
      - "/webjars/**"
      - "/swagger/**"
      - "/v1/lights"
      - "/v1/listener"
      - "/health/**"
      - "/assets/**"
      - "/error/**"
      - "/csrf/**"
      - "/docs/**"
